// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/transactions": {
    params: {};
  };
  "/categories": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/budgets": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/wallets": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/ai": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/transactions" | "/categories" | "/register" | "/budgets" | "/reports" | "/wallets" | "/login" | "/ai" | "/*";
  };
  "routes/[transactions]._index.jsx": {
    id: "routes/[transactions]._index";
    page: "/transactions";
  };
  "routes/[categories]._index.jsx": {
    id: "routes/[categories]._index";
    page: "/categories";
  };
  "routes/[register]._index.jsx": {
    id: "routes/[register]._index";
    page: "/register";
  };
  "routes/[budgets]._index.jsx": {
    id: "routes/[budgets]._index";
    page: "/budgets";
  };
  "routes/[reports]._index.jsx": {
    id: "routes/[reports]._index";
    page: "/reports";
  };
  "routes/[wallets]._index.jsx": {
    id: "routes/[wallets]._index";
    page: "/wallets";
  };
  "routes/[login]._index.jsx": {
    id: "routes/[login]._index";
    page: "/login";
  };
  "routes/[ai]._index.jsx": {
    id: "routes/[ai]._index";
    page: "/ai";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/[404]._index.jsx": {
    id: "routes/[404]._index";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/[transactions]._index": typeof import("./app/routes/[transactions]._index.jsx");
  "routes/[categories]._index": typeof import("./app/routes/[categories]._index.jsx");
  "routes/[register]._index": typeof import("./app/routes/[register]._index.jsx");
  "routes/[budgets]._index": typeof import("./app/routes/[budgets]._index.jsx");
  "routes/[reports]._index": typeof import("./app/routes/[reports]._index.jsx");
  "routes/[wallets]._index": typeof import("./app/routes/[wallets]._index.jsx");
  "routes/[login]._index": typeof import("./app/routes/[login]._index.jsx");
  "routes/[ai]._index": typeof import("./app/routes/[ai]._index.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/[404]._index": typeof import("./app/routes/[404]._index.jsx");
};